#!/usr/bin/env php
<?php


$DOCUMENT_ROOT = $_SERVER['DOCUMENT_ROOT'] = dirname(dirname(dirname(dirname(dirname(__DIR__))))).'/web';

//Подключаем автозагрузку классов композера.
require_once dirname($DOCUMENT_ROOT) . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Dumkaaa\BxOptimize\Cli\SymfonyOptimize());

$application->run();